### ISSUE TITLE
Error due to incomplete change

### ISSUE THREAD

**Issue by ishantvivek** [ResurrectionRemix/android_frameworks_base#108]
Error: [31mpackages/apps/Bluetooth/src/com/android/bluetooth/avrcp/Avrcp.java:659: error: cannot find symbol
            RemoteController.OnClientAvrcpUpdateListener {
Half changes is in packages_apps_bluetooth. And half in base 
http://review.cyanogenmod.org/#/c/143310/ .Update base to latest tag(r37), packages_apps_bluetooth is tracked from cyanogen git and framework_base from resurrection, because of that, error in compilation.

**Comment by akhilnarang** [comment]
Sorry, LP isn't supported anymore, revert that commit in BT repo if you want
