### ISSUE TITLE
Battery percentage (inside icon) not be display some times

### ISSUE THREAD

**Issue by bhb27** [ResurrectionRemix/android_frameworks_base#116]
I see this problem in some app's, like ES file, chrome, when the status bar is black, not all app with black status bar have this bug, flashfy or Titanium backup apps is ok...

Test this on a build of yesterday, notes the first time o build of last sunday. 

pic from chrome...
![screenshot_20160520-081335](https://cloud.githubusercontent.com/assets/13755892/15426279/e305ba0c-1e63-11e6-9c96-a71153697977.png)
![screenshot_20160520-081327](https://cloud.githubusercontent.com/assets/13755892/15426280/e30a8906-1e63-11e6-894f-9f3aba621c7c.png)

**Comment by varund7726** [comment]
Its fixed.....check latest commits and test please

**Comment by bhb27** [comment]
I see, will test and post here latter today... :+1:

**Comment by bhb27** [comment]
The problem persists on a Friday and a today build...

**Comment by varund7726** [comment]
yup this is cm issue
