### ISSUE TITLE
Cant build systemui package on lollipop5.1 branch

### ISSUE THREAD

**Issue by akorshun** [ResurrectionRemix/android_frameworks_base#132]
> target Java: SystemUI (/home/marvollo/rr5.1/out/target/common/obj/APPS/SystemUI_intermediates/classes)
frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/MusicTile.java:208: error: method does not override or implement a method from a supertype
        @Override
        ^
frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/MusicTile.java:211: error: method does not override or implement a method from a supertype
        @Override
        ^
frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/MusicTile.java:214: error: method does not override or implement a method from a supertype
        @Override
        ^
frameworks/base/packages/SystemUI/src/com/android/systemui/qs/tiles/MusicTile.java:217: error: method does not override or implement a method from a supertype
        @Override
        ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

getting this error while compiling rom, i think sth wrong with this commit https://github.com/ResurrectionRemix/android_frameworks_base/commit/acd9545f81b5723a2632cab139a1bee88e5c6999

**Comment by varund7726** [comment]
No it works here .

**Comment by akorshun** [comment]
@varund7726 maybe you can say why i and @FireLord1 get this error, i need to update some packages in my ubuntu?

**Comment by FireLord1** [comment]
@varund7726 nope my mate fixes your error to make build please try to fix.. we all love rr afterall

**Comment by Hacker432-Y550** [comment]
I have this error too
I'm using optimized lollipop branch
Why RR team doesn't care about it?

**Comment by akhilnarang** [comment]
@hacker432-y550 lollipop was deprecated months ago

**Comment by Hacker432-Y550** [comment]
So...no more RR lollipop? wtf?

**Comment by varund7726** [comment]
If you've fixed a lot of stuff, why not push them and make a pull request

**Comment by varund7726** [comment]
@Hacker432-Y550 and plz mind your tone and language ....
