### ISSUE TITLE
EACCES on external SD card on 20160909 klte build

### ISSUE THREAD

**Issue by github-cygwin** [ResurrectionRemix/android_frameworks_base#134]
Yesterday I rebuilt Resurrection Remix from scratch for three different
systems from identical sources (except the device specific ones, of
course), manta, w7, and klte.  While manta and w7 both work as expected,
I have a strange problem with klte:  For some reason only root is
allowed to write to the external SD card.  This was no problem with my
RR build from August 8.

Attached are two logcat outputs.

The first one has been taken while trying to take a photo using the 
Camera app.  It tries to write the newly taken photo to the SD card and
fails with EACCES.

The second logcat has been fetched during boot, started a bit late, 
perhaps.

I tried to find the cause for this problem, but this is apparently 
beyond my Android ken :(

Any chance you know what the problem here might be?

Thanks a lot,
Corinna
[Camera.logcat.txt](https://github.com/ResurrectionRemix/android_frameworks_base/files/465565/Camera.logcat.txt)
[Early.logcat.txt](https://github.com/ResurrectionRemix/android_frameworks_base/files/465566/Early.logcat.txt)

**Comment by DirkStorck** [comment]
The same problem I have with the unofficial RR builds being made by blackjuble.
I have although noticed that when I delete a file from ext sd card the amount of used space doesn't get updated. When I reboot the phone it amount is updated

**Comment by github-cygwin** [comment]
I found the cause for this problem.  Upstream patch 933fe28b6256c8cce55c488befb44150e06da48a in CyanogenMod/android_device_samsung_klte-common introduces this regression.  So this is in fact not a problem in RR, but in CM.  I reported the problem upstream.


Thanks,
Corinna

**Comment by DirkStorck** [comment]
In what nightly can we possibly expect to see that fix? Thank you!

**Comment by github-cygwin** [comment]
Patch 933fe28b has been reverted upstream for now, see
http://review.cyanogenmod.org/#/c/161777/

Corinna
