### ISSUE TITLE
unable to compile rom

### ISSUE THREAD

**Issue by vaishnavm217** [ResurrectionRemix/android_frameworks_base#136]
Hi everyone,
i am new to github so i dont know first of all if this is the right place for posting my query, so sorry if this is a wrong place
as RR has simplified the rom compilation in form of scripts, i always try to download all the sources again(deleting old and redownloading it again) and i compile roms it vm in my ok lappy (8gb ram i3)
whenever i try to compile, it takes nearly 8hrs, and moreover always fails...  before i used to do in ubuntu 16.04 so i switched to 14.04, but recent build had no kind of error, it had this:
make: *** No rule to make target `/home/vaishnav/rr/out/target/product/tomato/obj_arm/SHARED_LIBRARIES/libtime_genoff_intermediates/export_includes', needed by `/home/vaishnav/rr/out/target/product/tomato/obj_arm/SHARED_LIBRARIES/libandroid_servers_intermediates/import_includes'.  Stop.
make: Leaving directory `/home/vaishnav/rr'

[0;31m#### make failed to build some targets (08:18:39 (hh:mm:ss)) ####[0m

-how to fix this?
-is it normal to get warnings during compilations??
-can please someone teach me how to do this properly as i have compiled like 5 times and all times it has failed
i am attaching my build log, it will be really helpful if some helps me in solving this
[tomato-20160927.txt](https://github.com/ResurrectionRemix/android_frameworks_base/files/531313/tomato-20160927.txt)

**Comment by akhilnarang** [comment]
You haven't synced vendor/yu repository most probably

**Comment by vaishnavm217** [comment]
wait i thought scripts would automatically do thaat is asks for my device name
