### ISSUE TITLE
marshmellow bootloops when syncing repo to state on 2016-11-11

### ISSUE THREAD

**Issue by github-cygwin** [ResurrectionRemix/android_frameworks_base#139]
[2016-11-12-logcat.txt](https://github.com/ResurrectionRemix/android_frameworks_base/files/587392/2016-11-12-logcat.txt)
Hi,

the last stable state of the marshmallow  branch I built for two targets, klte and manta,
on 2016-10-26 work fine.

Yesterday and today I'm trying to build marshmallow RR for both targets, as well as for
the w7.  All these builds crash and remain in a bootloop.  I attached the logcat output of
of a single, complete loop.

That's for w7, the only logcat I had handy right now.  The manta output looked basically the same, especially the zygote SIGABRT is reproducibly the same.

Does that help to figure out the cause?  I'm not quite sure what part of the repo I'd have to bisect to find the culprit.

Thanks,
Corinna

**Comment by varund7726** [comment]
Does cm13 boot fine? My bacon boots fine here with Nov security patches

**Comment by varund7726** [comment]
I just pushed a couple of patches...let me know how it goes

**Comment by ashuy93** [comment]
[boot_log.txt](https://github.com/ResurrectionRemix/android_frameworks_base/files/587677/boot_log.txt)
Log attached!
even after those patches , it still bootloops.
This is happening after merging r74.
Yes, as Corinna mentioned above it gives, zygote SIGABRT.
all the builds after merging r74 are not booting. I might be wrong, but this what i have noticed


Device:Motorola Moto E 2014 (condor).

11-11 19:58:56.472   261   261 E Zygote  : Unable to stat fd 4 : Permission denied

11-11 19:58:56.472   261   261 F art     : art/runtime/jni_internal.cc:497] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:478: Unable to construct file descriptor table.

Thanks, 
Dashaanan

**Comment by varund7726** [comment]
Hi .can you try to see if cm13 with r74 merged boots or not?

**Comment by ashuy93** [comment]
Yes, I am building cm. i will let you know in about 30 minutes.

**Comment by ashuy93** [comment]
No, cm13 is also not booting :( with r74 merged.
similar, 
 art/runtime/jni_internal.cc:497] JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:478: Unable to construct file descriptor table.
Zygote SIGABRT.

any idea? what can be done?

Thanks, Dashaanan

**Comment by github-cygwin** [comment]
Hi varund7726.

your patches have done the trick, apparently, thanks a lot!  Zygote on the manta board now
did its job without crashing and the board booted into the system.  First test, Google Play
and XDA Labs still work.  I'll test on w7(*) and klte later today.

Thanks,
Corinna

(*) Curious enough, there are *no* post-r74 cm13 nightlies for the w7.  Uh oh...

**Comment by github-cygwin** [comment]
Hi varund7726,

w7 works fine, too.  klte is still building...


Corinna

**Comment by varund7726** [comment]
Ok good to know this.

**Comment by github-cygwin** [comment]
klte works as well.


Thanks a lot!
Corinna

**Comment by ashuy93** [comment]
Hi varund7726,
Nice to know the patch works..
But its not the case with condor, i will check if I'm wrong.
But let me know, if you find the solution

Thanks,
Dashaanan.

**Comment by varund7726** [comment]
@ashuy93 are you using Xposed? I have been told that Xposed causes bootloop with latest security patches

**Comment by ashuy93** [comment]
No..not at all..
 Stock RR, no changes at all..
After r74, cm also ain't booting.
Dunno what's wrong . I will check boot log again, might need your help, if you can :)

**Comment by ZdrowyGosciu** [comment]
Probably new Zygote patch (whitelist) is causing bootloop http://review.cyanogenmod.org/#/q/whitelist

**Comment by ashuy93** [comment]
@varund7726 repo synced RR again, still no luck and Latest cm13 nightly also not booting..
Yes @ZdrowyGosciu  maybe that's the reason

**Comment by ZdrowyGosciu** [comment]
@ashuy93: try this https://github.com/HealthyMarshmallow/android_frameworks_base/commit/0b5f4e5f762d4d8a85cab1a3085bf4296a97c4e5

**Comment by github-cygwin** [comment]
On Nov 14 02:05, Ashutosh R Yerdoni wrote:
> @varund7726 repo synced RR again, still no luck and Latest cm13 nightly also not booting..
> Yes @ZdrowyGosciu  maybe that's the reason

Well, that's weird.  As I wrote yesterday, it works now on three
different targets for me.  Any chance there's some target-specific
problem lurking?  Does logcat show something suspicious?


Corinna

**Comment by ashuy93** [comment]
@github-cygwin 
No target-specific problem, other roms have not yet merged r74 and zygote specific commits, so they are booting fine.
only cm13 and RR have merged these commits and device is not booting. :( 
Logcat gives zygote aborted SIGABRT

**Comment by github-cygwin** [comment]
@ashuy93,

that's what I meant when saying it's weird.  @varund7726 patches on 2016-11-12 fixed
the issue for all of my three targets.  Puzzeling.

Corinna

**Comment by ashuy93** [comment]
@ZdrowyGosciu thanks a lot it worked!.
@varund7726 https://github.com/HealthyMarshmallow/android_frameworks_base/commit/0b5f4e5f762d4d8a85cab1a3085bf4296a97c4e5 
using this boot went fine!
can someone explain what exactly were those reverted changes for??

**Comment by ZdrowyGosciu** [comment]
How about https://github.com/arter97/android_frameworks_base/commit/35724b039e7a990950100354d01467c05756de37?

**Comment by ashuy93** [comment]
@ZdrowyGosciu  this would be needed if Xposed framework needs to be supported in the ROM.
I am not using Xposed

**Comment by ZdrowyGosciu** [comment]
Right :smiley:

**Comment by SoUnd001** [comment]
I get the same error JNI FatalError called: frameworks/base/core/jni/com_android_internal_os_Zygote.cpp:478: Unable to construct file descriptor table.' and the rom dosen't boot any help?
