### ISSUE TITLE
recompile error(fixed)

### ISSUE THREAD

**Issue by micky387** [ResurrectionRemix/android_frameworks_base#27]
Hello. I build RR rom for note edge but i have problem when reompile "SystemUI_intermediates"
Here,the issue message.

frameworks/base/packages/SystemUI/src/com/android/systemui/statusbar/phone/StatusBarKeyguardViewManager.java:458: error: incompatible types
        return profile == null ? Profile.LockMode.DEFAULT : profile.getScreenLockMode();
                               ^
  required: int
  found:    Object
frameworks/base/packages/SystemUI/src/com/android/systemui/keyguard/KeyguardViewMediator.java:797: error: incomparable types: LockSettings and int
            if (profile.getScreenLockMode() == Profile.LockMode.DISABLE) {
                                            ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
build/core/java.mk:346 : la recette pour la cible « /home/micky387/RR/out/target/common/obj/APPS/SystemUI_intermediates/classes-full-debug.jar » a échouée
make: *** [/home/micky387/RR/out/target/common/obj/APPS/SystemUI_intermediates/classes-full-debug.jar] Erreur 41
make: *** Attente des tâches non terminées....
packages/apps/Settings/src/com/android/settings/profiles/actions/item/LockModeItem.java:65: error: incompatible types
        switch (profile.getScreenLockMode()) {
                                         ^
  required: int
  found:    LockSettings
packages/apps/Settings/src/com/android/settings/profiles/SetupActionsFragment.java:592: error: incomparable types: int and LockSettings
            if (LOCKMODE_MAPPING[i] == mProfile.getScreenLockMode()) {
                                    ^
packages/apps/Settings/src/com/android/settings/profiles/SetupActionsFragment.java:603: error: method setScreenLockMode in class Profile cannot be applied to given types;
                        mProfile.setScreenLockMode(LOCKMODE_MAPPING[item]);
                                ^
  required: LockSettings
  found: int
  reason: actual argument int cannot be converted to LockSettings by method invocation conversion
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
build/core/java.mk:346 : la recette pour la cible « /home/micky387/RR/out/target/common/obj/APPS/Settings_intermediates/classes-full-debug.jar » a échouée
make: *** [/home/micky387/RR/out/target/common/obj/APPS/Settings_intermediates/classes-full-debug.jar] Erreur 41
# In case value of PACKAGES is empty

What is the problem ?? Thanks

**Comment by akhilnarang** [comment]
We're fixing it ASAP, I have a test tomorrow, so can't do it right now
@varund7726 @westcripp @bdogg718k guess you guys can just update the repos

**Comment by micky387** [comment]
thanks guys for our work.
Best regards

**Comment by varund7726** [comment]
Fixed

Synd and build
