### ISSUE TITLE
Errors during assembly

### ISSUE THREAD

**Issue by ShevT** [ResurrectionRemix/android_frameworks_base#37]
The problem relates to the android_frameworks_opt_telephony.
Please, Fix it:

frameworks/opt/telephony/src/java/com/android/internal/telephony/SubscriptionController.java:380: error: cannot find symbol
                SubscriptionManager.USER_NETWORK_MODE));
                                   ^
  symbol:   variable USER_NETWORK_MODE
  location: class SubscriptionManager
frameworks/opt/telephony/src/java/com/android/internal/telephony/SubscriptionController.java:395: error: constructor SubscriptionInfo in class SubscriptionInfo cannot be applied to given types;
        return new SubscriptionInfo(id, iccId, simSlotIndex, displayName, carrierName,
               ^
  required: int,String,int,CharSequence,CharSequence,int,int,String,int,Bitmap,int,int,String,int,int
  found: int,String,int,String,String,int,int,String,int,Bitmap,int,int,String,int,int,int
  reason: actual and formal argument lists differ in length
frameworks/opt/telephony/src/java/com/android/internal/telephony/SubscriptionController.java:1755: error: cannot find symbol
        value.put(SubscriptionManager.USER_NETWORK_MODE, nwMode);
                                     ^
  symbol:   variable USER_NETWORK_MODE
  location: class SubscriptionManager
frameworks/opt/telephony/src/java/com/android/internal/telephony/SubscriptionController.java:1764: error: cannot find symbol
            return subInfo.mUserNwMode;
                          ^
  symbol:   variable mUserNwMode
  location: variable subInfo of type SubscriptionInfo
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

**Comment by akhilnarang** [comment]
https://github.com/ResurrectionRemix/platform_manifest/blob/lollipop5.1/default.xml#L369
@ShevT

**Comment by ShevT** [comment]
So what?
I've updated the repo. With him is not going to firmware.
Cyanogen 12.1 is going fine.

**Comment by akhilnarang** [comment]
Huh what? Didn't get you

**Comment by ShevT** [comment]
I have this.

Is not it necessary to add? https://github.com/CyanogenMod/android_frameworks_base/commit/41aa07c97820925ee8568fd9ec93cb5ae09f31d3

**Comment by akhilnarang** [comment]
Maybe, pick it, repos will be updated soon

**Comment by ShevT** [comment]
Ooh. I thought I was losing my mind. :)

**Comment by varund7726** [comment]
FIXED!

**Comment by ShevT** [comment]
Excellent work! Thank you.
