### ISSUE TITLE
SystemUI: Fix for CPU overload

### ISSUE THREAD

**Issue by sunsettrack4** [ResurrectionRemix/android_frameworks_base#76]
The SystemUI app causes lags and performance issues in RR v5.6.2. After the system has been used for a long time, SystemUI also crashes unexpectedly. It's not an device-specific problem, because many devices are affected, e.g. Samsung Galaxy Alpha / Galaxy S4. In addition to that, this issue doesn't appear in usual CM builds. Please provide a fix to improve the user experience. Thanks in advance.

https://plus.google.com/+AlokNandanNikhil/posts/RWPJtBaP9nX

**Comment by varund7726** [comment]
Its already fixed if the latest sources have been synced and the lag has gone...also this is nothing to do with cpu overload it was happening due to caching of qs tiles which has been improved
